"""Repair control characters left in list cells by broken escape handling.

Source TSVs were generated by an LLM from README files, and escapes such as
``\\u00e1`` or LaTeX's ``\\beta`` were decoded as escape sequences before the
values were written as Python list literals. ``ast.literal_eval`` then turns
``'Vel\\x00e1zquez'`` into a real NUL, which WEKO (Python 3.6 csv) cannot read.

Only corruptions with a single mechanical inverse are undone; the LLM output
itself is never corrected. Rules are applied in order to each list element:

R1  "\\u" and the high byte of \\uXXXX became one control character, the low
    two hex digits stayed: control char + 2 hex digits -> U+XXXX, when that is
    a letter, mark, number or symbol.
R2  LaTeX \\a \\b \\f \\v became BEL/BS/FF/VT: before a letter -> "\\a" etc.
R3  "\\t" and "\\r" became TAB/CR: TAB before a known LaTeX command name and
    CR before any letter -> "\\t"/"\\r".
R4  Any other control character -> the visible text "\\xNN".

A decoded "\\n" (LaTeX \\nu, \\nabla, ...) leaves LF, which cannot be told from
a real line break, so it is only reported for review and never changed.
"""

from __future__ import annotations

import ast
import csv
import os
import re
import unicodedata
from collections import Counter
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .metadata_pipeline import (
    FORBIDDEN_CONTROL_PATTERN,
    INPUT_FIELD_SIZE_LIMIT,
    detect_delimiter,
    resolve_delimiter,
)

# The generator rejects exactly what R4 makes visible.
CONTROL_PATTERN = FORBIDDEN_CONTROL_PATTERN

# \x07 \x08 \x0b \x0c are left to R2: LaTeX \vec, \backslash or \face would
# otherwise read as U+0BEC, U+08AC or U+0CAC.
BROKEN_UNICODE_ESCAPE = re.compile(r"([\x00-\x06\x0e-\x1f])([0-9a-fA-F]{2})")
BROKEN_LATEX_ESCAPE = re.compile(r"([\x07\x08\x0b\x0c])([A-Za-z])")
LATEX_ESCAPES = {"\x07": "\\a", "\x08": "\\b", "\x0b": "\\v", "\x0c": "\\f"}
# Commands whose leading \t was decoded to TAB. Real tabs precede words in
# code and tables, so only known command names (and every \text... command)
# are restored.
BROKEN_TAB_COMMAND = re.compile(
    r"\t(ext[A-Za-z]*|ilde|heta|au|imes|op|riangle|frac|anh?|o)(?![A-Za-z])"
)
# A real CR only precedes LF, so a CR followed by a letter is a decoded "\r"
# (e.g. \rho, or a path such as '\result').
BROKEN_CR_COMMAND = re.compile(r"\r([A-Za-z])")
RESTORABLE_CATEGORIES = frozenset("LMNS")
# LaTeX commands starting with "\n" whose decoded LF should be reviewed.
# Names that are also English words or prefixes at the start of a wrapped
# line (\ne, \ni, \neg "eg.", \nexists, \nmid, \nparallel, \nsubset,
# \nsim, \ncong) are left out: prose such as "computed in\nparallel" would
# match them.
SUSPECT_LF_COMMAND = re.compile(
    r"\n(u|abla|eq|ot|otin|orm|ull|atural|leq|geq|less|gtr|vdash"
    r"|leftarrow|rightarrow|Leftarrow|Rightarrow|earrow|warrow"
    r"|ewline|ewcommand|ewpage|ewtheorem|ewenvironment"
    r"|oindent|onumber|obreak|olimits|ormalsize|ormalfont)"
    r"(?![A-Za-z])"
)


@dataclass(frozen=True)
class CellRepair:
    record_number: int
    record_id: str
    column: str
    index: int
    rules: tuple[str, ...]
    before: str
    after: str


@dataclass(frozen=True)
class ReviewItem:
    """A list element that may hide a decoded "\\n"; it is not changed."""

    record_number: int
    record_id: str
    column: str
    index: int
    command: str
    context: str


def find_suspect_lf_commands(value: str) -> list[tuple[str, str]]:
    """Return (command, context) for each LF followed by a \\n... command."""
    return [
        ("\\n" + match.group(1), value[max(0, match.start() - 20) : match.end() + 20])
        for match in SUSPECT_LF_COMMAND.finditer(value)
    ]


def repair_value(value: str) -> tuple[str, tuple[str, ...]]:
    """Return the repaired value and the rules applied, in R1-R4 order.

    R4 also covers leading and trailing control characters that the
    generator's strip() would drop silently: in the source data they are
    decoded characters such as the "\\infty" of "\\infty-Diff", so dropping
    them would hide the corruption.
    """
    applied: list[str] = []

    def unicode_escape(match: re.Match[str]) -> str:
        character = chr((ord(match.group(1)) << 8) | int(match.group(2), 16))
        if unicodedata.category(character)[0] not in RESTORABLE_CATEGORIES:
            return match.group(0)
        applied.append("R1")
        return character

    def latex_escape(match: re.Match[str]) -> str:
        applied.append("R2")
        return LATEX_ESCAPES[match.group(1)] + match.group(2)

    def latex_command(prefix: str) -> Callable[[re.Match[str]], str]:
        def replace(match: re.Match[str]) -> str:
            applied.append("R3")
            return prefix + match.group(1)

        return replace

    def visible(match: re.Match[str]) -> str:
        applied.append("R4")
        return f"\\x{ord(match.group(0)):02x}"

    value = BROKEN_UNICODE_ESCAPE.sub(unicode_escape, value)
    value = BROKEN_LATEX_ESCAPE.sub(latex_escape, value)
    value = BROKEN_TAB_COMMAND.sub(latex_command("\\t"), value)
    value = BROKEN_CR_COMMAND.sub(latex_command("\\r"), value)
    value = CONTROL_PATTERN.sub(visible, value)
    return value, tuple(dict.fromkeys(applied))


def _literal_list(cell: str) -> list[Any] | None:
    """Parse a cell the way the generator does; None if it is not a list."""
    text = cell.strip()
    if not (text.startswith("[") and text.endswith("]")):
        return None
    try:
        parsed = ast.literal_eval(text)
    except (SyntaxError, ValueError, TypeError, MemoryError, RecursionError):
        return None
    return parsed if isinstance(parsed, list) else None


def repair_cell(cell: str) -> tuple[str, list[tuple[int, tuple[str, ...], str, str]]]:
    """Repair the string elements of a list cell; other cells are unchanged.

    Returns the new cell text and (index, rules, before, after) per changed
    element. An unchanged cell keeps its exact text.
    """
    elements = _literal_list(cell)
    if elements is None:
        return cell, []
    changes: list[tuple[int, tuple[str, ...], str, str]] = []
    repaired: list[Any] = []
    for index, element in enumerate(elements):
        if isinstance(element, str):
            new, rules = repair_value(element)
            if new != element:
                changes.append((index, rules, element, new))
            element = new
        repaired.append(element)
    return (repr(repaired) if changes else cell), changes


def same_file(path: Path, other: Path) -> bool:
    if path.exists() and other.exists():
        return os.path.samefile(path, other)
    return path.resolve() == other.resolve()


def repair_file(
    input_path: Path,
    output_path: Path,
    *,
    delimiter: str = "auto",
    id_column: str | None = "corpusid",
    keep_mtime: bool = True,
    reviews: list[ReviewItem] | None = None,
) -> list[CellRepair]:
    """Write input_path to output_path with list cells repaired.

    List elements that may hide a decoded "\\n" are appended to reviews.

    Record numbers count the header as 1 and skip blank lines, like the
    generator's row errors. The output is written to a temporary file and
    moved into place, so a failed run leaves no partial output. With
    keep_mtime, output_path gets input_path's modification time so ZIPs
    generated from unchanged rows keep their SHA-256 in the import ledger.
    """
    if same_file(input_path, output_path):
        raise ValueError("--output must differ from --input")
    separator = resolve_delimiter(delimiter) or detect_delimiter(input_path)
    with input_path.open("rb") as raw:
        has_bom = raw.read(3) == b"\xef\xbb\xbf"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = output_path.with_name(f".{output_path.name}.tmp")
    repairs: list[CellRepair] = []
    previous_limit = csv.field_size_limit(INPUT_FIELD_SIZE_LIMIT)
    try:
        with (
            input_path.open("r", encoding="utf-8-sig", newline="") as source,
            temporary_path.open(
                "w", encoding="utf-8-sig" if has_bom else "utf-8", newline=""
            ) as target,
        ):
            reader = csv.reader(source, delimiter=separator)
            writer = csv.writer(target, delimiter=separator, lineterminator="\n")
            header = next(reader, None)
            if header is not None:
                writer.writerow(header)
                id_index = header.index(id_column) if id_column in header else None
                record_number = 1
                for cells in reader:
                    if not cells:
                        # csv.DictReader skips blank lines without numbering them.
                        writer.writerow(cells)
                        continue
                    record_number += 1
                    repairs.extend(
                        _repair_row(cells, header, record_number, id_index, reviews)
                    )
                    writer.writerow(cells)
        os.replace(temporary_path, output_path)
    finally:
        csv.field_size_limit(previous_limit)
        temporary_path.unlink(missing_ok=True)
    if keep_mtime:
        stat = input_path.stat()
        os.utime(output_path, ns=(stat.st_atime_ns, stat.st_mtime_ns))
    return repairs


def _repair_row(
    cells: list[str],
    header: list[str],
    record_number: int,
    id_index: int | None,
    reviews: list[ReviewItem] | None = None,
) -> list[CellRepair]:
    """Repair cells in place and return what changed."""
    record_id = (
        cells[id_index] if id_index is not None and id_index < len(cells) else ""
    )
    repairs: list[CellRepair] = []
    for position, cell in enumerate(cells):
        column = header[position] if position < len(header) else ""
        if reviews is not None:
            for index, element in enumerate(_literal_list(cell) or []):
                if isinstance(element, str):
                    reviews.extend(
                        ReviewItem(
                            record_number, record_id, column, index, command, context
                        )
                        for command, context in find_suspect_lf_commands(element)
                    )
        new_cell, changes = repair_cell(cell)
        if not changes:
            continue
        cells[position] = new_cell
        repairs.extend(
            CellRepair(record_number, record_id, column, index, rules, before, after)
            for index, rules, before, after in changes
        )
    return repairs


def _write_tsv_atomically(
    path: Path, header: list[str], rows: list[list[object]]
) -> None:
    """Write a UTF-8 BOM TSV via a temporary file, so a failure keeps the old one."""
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_path = path.with_name(f".{path.name}.tmp")
    try:
        with temporary_path.open("w", encoding="utf-8-sig", newline="") as file_obj:
            writer = csv.writer(file_obj, delimiter="\t", lineterminator="\n")
            writer.writerow(header)
            writer.writerows(rows)
        os.replace(temporary_path, path)
    finally:
        temporary_path.unlink(missing_ok=True)


def write_repair_report(repairs: list[CellRepair], report_path: Path) -> None:
    rows: list[list[object]] = [
        [
            repair.record_number,
            repair.record_id,
            repair.column,
            repair.index,
            ",".join(repair.rules),
            # repr makes the control characters in "before" visible.
            repr(repair.before),
            repair.after,
        ]
        for repair in repairs
    ]
    _write_tsv_atomically(
        report_path,
        ["record_no", "id", "column", "list_index", "rules", "before", "after"],
        rows,
    )


def write_review_report(reviews: list[ReviewItem], review_path: Path) -> None:
    rows: list[list[object]] = [
        [
            review.record_number,
            review.record_id,
            review.column,
            review.index,
            review.command,
            repr(review.context),
        ]
        for review in reviews
    ]
    _write_tsv_atomically(
        review_path,
        ["record_no", "id", "column", "list_index", "command", "context"],
        rows,
    )


def count_rules(repairs: list[CellRepair]) -> Counter[str]:
    return Counter(rule for repair in repairs for rule in repair.rules)
